#!/usr/bin/env python3
"""Generate a deterministic Markdown report from append-only learning events."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def load_events(path: Path) -> list[dict]:
    events: list[dict] = []
    if not path.exists():
        return events
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip():
            continue
        try:
            events.append(json.loads(raw))
        except json.JSONDecodeError as exc:
            raise ValueError(f"{path}:{line_number}: {exc}") from exc
    return events


def render(events: list[dict]) -> str:
    retired: set[str] = set()
    for event in events:
        if event.get("event") == "retire" or event.get("status") == "retired":
            retired.update(event.get("supersedes", []))

    def section(title: str, rows: list[dict]) -> list[str]:
        lines = [f"## {title}", ""]
        if not rows:
            lines.extend(["_None._", ""])
            return lines
        for row in rows:
            marker = " (retired)" if row["id"] in retired else ""
            lines.append(f"### `{row['id']}`{marker}")
            lines.append("")
            lines.append(f"- **Decision:** {row['decision']}")
            lines.append(f"- **Observed:** {row['observation']}")
            lines.append(
                f"- **Stage / signal:** `{row['stage']}` / `{row['signal_type']}`"
            )
            if row.get("episode"):
                lines.append(f"- **Episode:** `{row['episode']}`")
            evidence = row.get("evidence") or []
            if evidence:
                lines.append("- **Evidence:** " + "; ".join(evidence))
            if row.get("supersedes"):
                lines.append("- **Supersedes:** " + ", ".join(row["supersedes"]))
            lines.append("")
        return lines

    active = [e for e in events if e.get("id") not in retired]
    rules = [e for e in active if e.get("scope") == "system_rule" and e.get("status") == "promoted"]
    candidates = [e for e in active if e.get("scope") == "system_candidate"]
    channel = [e for e in active if e.get("scope") == "channel"]
    episode = [e for e in active if e.get("scope") == "episode"]

    lines = [
        "# Learning Report",
        "",
        "Generated from `knowledge/learnings.jsonl`. Do not edit this file manually.",
        "",
        f"Total events: **{len(events)}**. Active promoted system rules: **{len(rules)}**.",
        "",
    ]
    lines += section("Promoted system rules", rules)
    lines += section("System candidates", candidates)
    lines += section("Channel defaults", channel)
    lines += section("Episode observations", episode)
    lines += ["## Event index", ""]
    for event in events:
        lines.append(
            f"- `{event['recorded_at']}` — `{event['event']}` — `{event['id']}` — {event['decision']}"
        )
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    root = repo_root()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--store", type=Path, default=root / "knowledge" / "learnings.jsonl")
    parser.add_argument("--out", type=Path, default=root / "knowledge" / "LEARNING_REPORT.md")
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    expected = render(load_events(args.store))
    if args.check:
        actual = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if actual != expected:
            print(f"stale learning report: run {Path(__file__).name}", file=sys.stderr)
            return 1
        print("learning report is current")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(expected, encoding="utf-8")
    print(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
